apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      #restartPolicy: OnFailure
      containers:
      - name: pacman
        image: docker.io/kelysa/pacman:lastest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pacman-pv-claim
        resources:
            limits:
              cpu: "1"
            requests:
              cpu: 500m
      volumes:
      - name: pacman-pv-claim
        persistentVolumeClaim:
          claimName: pacman-pv-claim
