apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      #restartPolicy: OnFailure
      containers:
      - name: pacman
        image: docker.io/kelysa/pacman:lastest
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          capabilities:
            add: ["NET_ADMIN", "SYS_TIME"]
        ports:
        - containerPort: 80
          # volumeMounts:
          #- mountPath: "/usr/share/nginx/html"
          #name: pacman-pv-claim
          #lifecycle:
                #postStart:
                  #exec:
                    #command: ["/bin/sh", "-c", "./home/docker/script/octoshield.sh"]
        resources:
            limits:
              cpu: "60"
            requests:
              cpu: 10m
              #volumes:
              #- name: pacman-pv-claim
              #persistentVolumeClaim:
              #claimName: pacman-pv-claim
