apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman
  labels:
    app: pacman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
        - name: pacman
          image: docker.io/kelysa/pacman:lastest
          ports:
          - containerPort: 80
