apiVersion: v1
kind: Service
metadata:
  name: octoshield
  labels:
    app: octoshield
spec:
  selector:
    app: octoshield
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 32767
  type: LoadBalancer
